spring.application.name=tour-booking-backend

Spring.datasource.url = jdbc:mysql://127.0.0.1:3306/tour_booking_db
spring.datasource.username=root
spring.datasource.password=0387983204lL

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true